name: Node CI

on:
  push:
    branches: [main, cicd-actions]
  pull_request:
    branches: [main]

jobs:
  robot_tests:
    name: robot-tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - run: pip3 install robotframework
      - run: sh ./run_script.sh

  test_pull_request:
    name: test_pullrequests
    needs: robot_tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Test dependencies
        run: npm test
      - name: Build dependencies
        run: npm run build
  # docker:
  #   name: Docker build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build and Push Docker Image
  #       uses: mr-smithers-excellent/docker-build-push@v5
  #       with:
  #         image: abdualiandrei/fullstack-renting-application
  #         registry: docker.io
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
